import "./delete";
import "./get";
import "./registration";
import "./put";
import "./get_user_role";
import "./login";
import "./logout";
import "./reset-password";
import "./reset-password-confirm";
