import "./delete";
import "./get";
import "./registration";
import "./put";
import "./login";
import "./logout";
import "./reset-password";
import "./reset-password-confirm";
import "./change-default-credentials";
